version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      MONGO_URI: mongodb://mongo:27017/devsecops
    depends_on:
      - mongo
    networks:
      - devops-net

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      - devops-net

  
networks:
  devops-net:
