version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      MONGO_URI: mongodb://mongo:27017/devsecops
    depends_on:
      - mongo
    networks:
      - devops-net
    labels:
      - "logging=promtail"

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      - devops-net
    labels:
      - "logging=promtail"

  loki:
    image: grafana/loki:2.9.2
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - devops-net

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/hostname:/etc/hostname:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - devops-net

networks:
  devops-net:

volumes:
  mongo_data:
