version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      MONGO_URI: mongodb://mongo:27017/devsecops
    depends_on:
      - mongo
    networks:
      - devops-net

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      - devops-net

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Enables Jenkins to run Docker inside container
    networks:
      - devops-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - devops-net

volumes:
  jenkins_data:
  grafana_data:

networks:
  devops-net:
